### ISSUE TITLE
Incorrect behavior of togglepause

### ISSUE THREAD

**Issue by TAforever** [jbirnick/waybar-timer#1]
Thanks for your work, I have been using polybar timer for a long time and now waybar. I noticed that togglepause often instead of pausing the timer resets the time and the timer goes off

https://github.com/user-attachments/assets/c9fe5eda-111c-491e-a819-47041fb3626a

**Comment by jbirnick** [comment]
Yes I've also been noticing this. And also other bugs where when you scroll to increase the timer, it would just stop the timer sometimes.

I haven't yet figured out what exactly the issue is. Two things:
- The calling/display architecture is different for waybar compared to polybar. I could do it the same way as polybar and check if that kills some bugs.
- There might be a data race in file reading/writing, because that's the way the timer stores its value lol.

I will have a look at this when I find time. If someone else looks into this and finds the issue, please report here.

**Comment by TAforever** [comment]
Yesterday I decided to experiment with this and just copied the script and customization from polybar and it works flawlessly, but sometimes for some reason the timer fails. I also noticed that if I remove  `5` from line 
`"exec":  "~/.config/waybar/scripts/waybar-timer.sh tail ' ' 5",` the togglepause problem reappears. I hope this information will be useful to you

**Comment by jbirnick** [comment]
Yeah the main issue seems to be a data race because waybar doesn't do what it says in the docs:
https://github.com/Alexays/Waybar/issues/1681
Which makes there `exec-on-event` feature completely useless lol.

The issue hasn't been fixed in 2 years. I made a comment there now. If doesn't get fixed soon I guess I have to roll back to the polybar mechanism. (Can I just say again how stupid this is, waybar "adds" a feature that makes it nicer to do such updates but then implements it completely wrongly which renders it useless and then they don't fix it when everybody complains? Eieiei.)

**Comment by jbirnick** [comment]
Ok I guess it won't get fixed in polybar so we have to modify the setup a bit. But that's actually not so complicated.

The bigger issue is how to fix all the data races that are going on. There doesn't seem to be an elegant way to handle this in bash.. :/ I could easily write a Rust program (or maybe also a Python script) which works flawless in all situations, but somehow the idea always was to just a have a bash script which everyone can run without headache of installing any binaries.

**Comment by TAforever** [comment]
Yeah, it's probably not very practical to make a binary for a custom module, but I'd still use it if it works without errors. Have you considered making a pull request for waybar to have the timer out of the box? Or do you think it won't be accepted?

**Comment by jbirnick** [comment]
Yeah there is a pull request that fixes it but it hasn't been merged since 2 years or so and the maintainer is not responding, also tried to reach him via email. I'll consider making a binary.

**Comment by jbirnick** [comment]
Okay I made a binary now. Please test it and let me know if you have any issues!

**Comment by TAforever** [comment]
Hi, thanks, everything seems to work fine, but I have a few wishes.

1. Previously, in polybar and waybar, I added the `paplay /usr/share/sounds/freedesktop/stereo/complete.oga` command to produce a sound after the timer expires, but now it seems that this cannot be done. Could you add this command?

2. Previously, in polybar and waybar, the timer continued to work after restarting the bar, but now it is reset. Is it possible to fix this?

3. Previously, when the timer was a script, I removed `0` so that it would not be output when the timer was not set, also in polybar this was the default. Is it possible to do something about this?

**Comment by jbirnick** [comment]
1. I now changed it to have commands again. Please try it out.

2. Previously the state was stored in a file, hence the persistence. (Though it was stored in `/tmp/`, so it should have been cleared after a computer restart?!) Now the state is stored in the memory of the tail process. You could try to work around that but I don't think it's worth the hassle. Why would you want to persist a timer over restarts?

3. Well the default format is `{icon} {script output}`. So when the script output is empty, it's asymmetrical. You can only fix the asymmetry by incorporating the icon into the script output, but that makes a less nice config. If you want to remove the zero nevertheless and have the asymmetry, just edit the code again. (Now it's Rust so it's a bit more complicated, but you can do it!)

**Comment by TAforever** [comment]
Yes, everything is working perfectly! Actually, I just edited the bar a lot and got used to the behavior that the timer keeps running after restarting the bar, but it's not something much needed. As for displaying `0`, I'm also used to the fact that it hasn't been displayed since using polybar, it just seems to me that it's more aesthetically pleasing, but this is again a personal preference. I'm completely satisfied with how it works now, so there's no need to change anything.
Thank you!

**Comment by TAforever** [comment]
It seems you made a mistake in the README by removing `1`. Scroll up doesn't work without it.
```json
"on-scroll-up": "/path/to/waybar-timer increase 60 || /path/to/waybar-timer new 'notify-send -u critical \"Timer expired\"'",
```

**Comment by jbirnick** [comment]
Fixed, thanks!
